# Generated by Django 4.2.2 on 2023-06-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='NA', null=True)),
                ('city', models.CharField(default='NA', null=True)),
                ('country', models.CharField(default='NA', null=True)),
                ('postalCode', models.IntegerField(null=True)),
                ('aboutMe', models.CharField(default='NA', null=True)),
                ('userName', models.CharField(default='NA', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
